export const CATEGORIES = [
  // Home Services
  { slug: "home-services", label: "Home Services", icon: "toolbox" },
  { slug: "electrician", label: "Electrician", icon: "toolbox" },
  { slug: "plumber", label: "Plumber", icon: "toolbox" },
  { slug: "carpenter", label: "Carpenter", icon: "toolbox" },
  { slug: "painter", label: "Painter", icon: "toolbox" },
  { slug: "mason", label: "Mason", icon: "toolbox" },
  { slug: "tiles-installer", label: "Tiles Installer", icon: "toolbox" },
  { slug: "pop-false-ceiling-worker", label: "POP/False Ceiling Worker", icon: "toolbox" },
  { slug: "welder", label: "Welder", icon: "toolbox" },
  { slug: "glass-installer", label: "Glass Installer", icon: "toolbox" },
  { slug: "aluminium-fabricator", label: "Aluminium Fabricator", icon: "toolbox" },
  { slug: "steel-fabricator", label: "Steel Fabricator", icon: "toolbox" },
  { slug: "roofer", label: "Roofer", icon: "toolbox" },
  { slug: "waterproofing-expert", label: "Waterproofing Expert", icon: "toolbox" },
  { slug: "pest-control", label: "Pest Control", icon: "toolbox" },

  // Cleaning Services
  { slug: "deep-cleaning", label: "Deep Cleaning", icon: "toolbox" },
  { slug: "home-cleaning", label: "Home Cleaning", icon: "toolbox" },
  { slug: "sofa-cleaning", label: "Sofa Cleaning", icon: "toolbox" },
  { slug: "carpet-cleaning", label: "Carpet Cleaning", icon: "toolbox" },
  { slug: "mattress-cleaning", label: "Mattress Cleaning", icon: "toolbox" },
  { slug: "water-tank-cleaning", label: "Water Tank Cleaning", icon: "toolbox" },
  { slug: "septic-tank-cleaning", label: "Septic Tank Cleaning", icon: "toolbox" },
  { slug: "borewell-technician", label: "Borewell Technician", icon: "toolbox" },

  { slug: "handyman", label: "Handyman", icon: "toolbox" },
  { slug: "locksmith", label: "Locksmith", icon: "toolbox" },
  { slug: "cctv-installer", label: "CCTV Installer", icon: "toolbox" },
  { slug: "solar-panel-installer", label: "Solar Panel Installer", icon: "toolbox" },
  { slug: "inverter-technician", label: "Inverter Technician", icon: "toolbox" },
  { slug: "ac-technician", label: "AC Technician", icon: "toolbox" },
  { slug: "refrigerator-technician", label: "Refrigerator Technician", icon: "toolbox" },
  { slug: "washing-machine-technician", label: "Washing Machine Technician", icon: "toolbox" },
  { slug: "microwave-repair", label: "Microwave Repair", icon: "toolbox" },
  { slug: "tv-repair", label: "TV Repair", icon: "toolbox" },
  { slug: "geyser-repair", label: "Geyser Repair", icon: "toolbox" },
  { slug: "chimney-repair", label: "Chimney Repair", icon: "toolbox" },
  { slug: "ro-water-purifier-technician", label: "RO Water Purifier Technician", icon: "toolbox" },

  // Construction & Interior
  { slug: "construction-interior", label: "Construction & Interior", icon: "toolbox" },
  { slug: "architect", label: "Architect", icon: "toolbox" },
  { slug: "civil-engineer", label: "Civil Engineer", icon: "toolbox" },
  { slug: "interior-designer", label: "Interior Designer", icon: "toolbox" },
  { slug: "interior-decorator", label: "Interior Decorator", icon: "toolbox" },
  { slug: "structural-engineer", label: "Structural Engineer", icon: "toolbox" },
  { slug: "quantity-surveyor", label: "Quantity Surveyor", icon: "toolbox" },
  { slug: "site-supervisor", label: "Site Supervisor", icon: "toolbox" },
  { slug: "building-contractor", label: "Building Contractor", icon: "toolbox" },
  { slug: "modular-kitchen-designer", label: "Modular Kitchen Designer", icon: "toolbox" },
  { slug: "furniture-maker", label: "Furniture Maker", icon: "toolbox" },
  { slug: "landscape-designer", label: "Landscape Designer", icon: "toolbox" },

  // Technology & IT
  { slug: "technology-it", label: "Technology & IT", icon: "toolbox" },
  { slug: "software-engineer", label: "Software Engineer", icon: "toolbox" },
  { slug: "full-stack-developer", label: "Full Stack Developer", icon: "toolbox" },
  { slug: "frontend-developer", label: "Frontend Developer", icon: "toolbox" },
  { slug: "backend-developer", label: "Backend Developer", icon: "toolbox" },
  { slug: "mobile-app-developer", label: "Mobile App Developer", icon: "toolbox" },
  { slug: "ai-engineer", label: "AI Engineer", icon: "toolbox" },
  { slug: "machine-learning-engineer", label: "Machine Learning Engineer", icon: "toolbox" },
  { slug: "data-scientist", label: "Data Scientist", icon: "toolbox" },
  { slug: "data-analyst", label: "Data Analyst", icon: "toolbox" },
  { slug: "devops-engineer", label: "DevOps Engineer", icon: "toolbox" },
  { slug: "cloud-engineer", label: "Cloud Engineer", icon: "toolbox" },
  { slug: "cybersecurity-expert", label: "Cybersecurity Expert", icon: "toolbox" },
  { slug: "ui-ux-designer", label: "UI/UX Designer", icon: "toolbox" },
  { slug: "web-designer", label: "Web Designer", icon: "toolbox" },
  { slug: "website-developer", label: "Website Developer", icon: "toolbox" },
  { slug: "wordpress-developer", label: "WordPress Developer", icon: "toolbox" },
  { slug: "shopify-developer", label: "Shopify Developer", icon: "toolbox" },
  { slug: "game-developer", label: "Game Developer", icon: "toolbox" },
  { slug: "qa-tester", label: "QA Tester", icon: "toolbox" },
  { slug: "blockchain-developer", label: "Blockchain Developer", icon: "toolbox" },
  { slug: "database-administrator", label: "Database Administrator", icon: "toolbox" },
  { slug: "network-engineer", label: "Network Engineer", icon: "toolbox" },
  { slug: "it-support", label: "IT Support", icon: "toolbox" },
  { slug: "computer-repair-technician", label: "Computer Repair Technician", icon: "toolbox" },
  { slug: "laptop-repair", label: "Laptop Repair", icon: "toolbox" },
  { slug: "printer-repair", label: "Printer Repair", icon: "toolbox" },

  // Design & Creative
  { slug: "design-creative", label: "Design & Creative", icon: "toolbox" },
  { slug: "graphic-designer", label: "Graphic Designer", icon: "toolbox" },
  { slug: "logo-designer", label: "Logo Designer", icon: "toolbox" },
  { slug: "motion-graphics-designer", label: "Motion Graphics Designer", icon: "toolbox" },
  { slug: "video-editor", label: "Video Editor", icon: "toolbox" },
  { slug: "animator", label: "Animator", icon: "toolbox" },
  { slug: "3d-artist", label: "3D Artist", icon: "toolbox" },
  { slug: "cad-designer", label: "CAD Designer", icon: "toolbox" },
  { slug: "illustrator", label: "Illustrator", icon: "toolbox" },
  { slug: "photoshop-expert", label: "Photoshop Expert", icon: "toolbox" },
  { slug: "photographer", label: "Photographer", icon: "camera" },
  { slug: "videographer", label: "Videographer", icon: "video" },
  { slug: "drone-photographer", label: "Drone Photographer", icon: "toolbox" },
  { slug: "photo-editor", label: "Photo Editor", icon: "toolbox" },

  // Digital Marketing
  { slug: "digital-marketing", label: "Digital Marketing", icon: "toolbox" },
  { slug: "seo-expert", label: "SEO Expert", icon: "toolbox" },
  { slug: "sem-expert", label: "SEM Expert", icon: "toolbox" },
  { slug: "social-media-manager", label: "Social Media Manager", icon: "toolbox" },
  { slug: "content-writer", label: "Content Writer", icon: "toolbox" },
  { slug: "copywriter", label: "Copywriter", icon: "toolbox" },
  { slug: "email-marketer", label: "Email Marketer", icon: "toolbox" },
  { slug: "performance-marketer", label: "Performance Marketer", icon: "toolbox" },
  { slug: "influencer-manager", label: "Influencer Manager", icon: "toolbox" },
  { slug: "brand-consultant", label: "Brand Consultant", icon: "toolbox" },
  { slug: "marketing-consultant", label: "Marketing Consultant", icon: "toolbox" },

  // Education & Training
  { slug: "education-training", label: "Education & Training", icon: "toolbox" },
  { slug: "home-tutor", label: "Home Tutor", icon: "book" },
  { slug: "online-tutor", label: "Online Tutor", icon: "book" },
  { slug: "spoken-english-trainer", label: "Spoken English Trainer", icon: "book" },
  { slug: "ielts-trainer", label: "IELTS Trainer", icon: "book" },
  { slug: "neet-coach", label: "NEET Coach", icon: "book" },
  { slug: "jee-coach", label: "JEE Coach", icon: "book" },
  { slug: "upsc-coach", label: "UPSC Coach", icon: "book" },
  { slug: "coding-teacher", label: "Coding Teacher", icon: "book" },
  { slug: "music-teacher", label: "Music Teacher", icon: "music" },
  { slug: "dance-teacher", label: "Dance Teacher", icon: "toolbox" },
  { slug: "yoga-instructor", label: "Yoga Instructor", icon: "dumbbell" },
  { slug: "gym-trainer", label: "Gym Trainer", icon: "dumbbell" },
  { slug: "swimming-coach", label: "Swimming Coach", icon: "toolbox" },
  { slug: "chess-coach", label: "Chess Coach", icon: "toolbox" },
  { slug: "cricket-coach", label: "Cricket Coach", icon: "toolbox" },
  { slug: "football-coach", label: "Football Coach", icon: "toolbox" },
  { slug: "badminton-coach", label: "Badminton Coach", icon: "toolbox" },
  { slug: "tennis-coach", label: "Tennis Coach", icon: "toolbox" },

  // Beauty & Wellness
  { slug: "beauty-wellness", label: "Beauty & Wellness", icon: "toolbox" },
  { slug: "barber", label: "Barber", icon: "toolbox" },
  { slug: "hair-stylist", label: "Hair Stylist", icon: "toolbox" },
  { slug: "makeup-artist", label: "Makeup Artist", icon: "toolbox" },
  { slug: "mehendi-artist", label: "Mehendi Artist", icon: "toolbox" },
  { slug: "nail-artist", label: "Nail Artist", icon: "toolbox" },
  { slug: "beautician", label: "Beautician", icon: "toolbox" },
  { slug: "spa-therapist", label: "Spa Therapist", icon: "toolbox" },
  { slug: "massage-therapist", label: "Massage Therapist", icon: "toolbox" },
  { slug: "skincare-specialist", label: "Skincare Specialist", icon: "toolbox" },
  { slug: "bridal-makeup-artist", label: "Bridal Makeup Artist", icon: "toolbox" },
  { slug: "tattoo-artist", label: "Tattoo Artist", icon: "toolbox" },
  { slug: "piercing-specialist", label: "Piercing Specialist", icon: "toolbox" },

  // Healthcare
  { slug: "healthcare", label: "Healthcare", icon: "toolbox" },
  { slug: "doctor", label: "Doctor", icon: "toolbox" },
  { slug: "dentist", label: "Dentist", icon: "toolbox" },
  { slug: "physiotherapist", label: "Physiotherapist", icon: "toolbox" },
  { slug: "nurse", label: "Nurse", icon: "toolbox" },
  { slug: "caregiver", label: "Caregiver", icon: "toolbox" },
  { slug: "elderly-care", label: "Elderly Care", icon: "toolbox" },
  { slug: "baby-care", label: "Baby Care", icon: "toolbox" },
  { slug: "nutritionist", label: "Nutritionist", icon: "toolbox" },
  { slug: "dietitian", label: "Dietitian", icon: "toolbox" },
  { slug: "psychologist", label: "Psychologist", icon: "toolbox" },
  { slug: "counsellor", label: "Counsellor", icon: "toolbox" },
  { slug: "speech-therapist", label: "Speech Therapist", icon: "toolbox" },
  { slug: "occupational-therapist", label: "Occupational Therapist", icon: "toolbox" },

  // Automobile
  { slug: "automobile", label: "Automobile", icon: "toolbox" },
  { slug: "car-wash", label: "Car Wash", icon: "toolbox" },
  { slug: "bike-wash", label: "Bike Wash", icon: "toolbox" },
  { slug: "car-mechanic", label: "Car Mechanic", icon: "toolbox" },
  { slug: "bike-mechanic", label: "Bike Mechanic", icon: "toolbox" },
  { slug: "auto-electrician", label: "Auto Electrician", icon: "toolbox" },
  { slug: "denting-painting", label: "Denting & Painting", icon: "toolbox" },
  { slug: "car-detailing", label: "Car Detailing", icon: "toolbox" },
  { slug: "wheel-alignment", label: "Wheel Alignment", icon: "toolbox" },
  { slug: "tyre-repair", label: "Tyre Repair", icon: "toolbox" },
  { slug: "battery-service", label: "Battery Service", icon: "toolbox" },
  { slug: "towing-service", label: "Towing Service", icon: "toolbox" },
  { slug: "driver", label: "Driver", icon: "toolbox" },
  { slug: "chauffeur", label: "Chauffeur", icon: "toolbox" },

  // Event Services
  { slug: "event-services", label: "Event Services", icon: "calendar" },
  { slug: "wedding-planner", label: "Wedding Planner", icon: "calendar" },
  { slug: "event-planner", label: "Event Planner", icon: "calendar" },
  { slug: "caterer", label: "Caterer", icon: "toolbox" },
  { slug: "decorator", label: "Decorator", icon: "toolbox" },
  { slug: "balloon-decorator", label: "Balloon Decorator", icon: "toolbox" },
  { slug: "tent-house", label: "Tent House", icon: "toolbox" },
  { slug: "lighting-service", label: "Lighting Service", icon: "toolbox" },

  // Business Services
  { slug: "business-services", label: "Business Services", icon: "toolbox" },
  { slug: "chartered-accountant", label: "Chartered Accountant", icon: "toolbox" },
  { slug: "tax-consultant", label: "Tax Consultant", icon: "toolbox" },
  { slug: "gst-consultant", label: "GST Consultant", icon: "toolbox" },
  { slug: "company-secretary", label: "Company Secretary", icon: "toolbox" },
  { slug: "lawyer", label: "Lawyer", icon: "toolbox" },
  { slug: "hr-consultant", label: "HR Consultant", icon: "toolbox" },
  { slug: "recruiter", label: "Recruiter", icon: "toolbox" },
  { slug: "business-consultant", label: "Business Consultant", icon: "toolbox" },
  { slug: "financial-advisor", label: "Financial Advisor", icon: "toolbox" },
  { slug: "insurance-advisor", label: "Insurance Advisor", icon: "toolbox" },

  // Delivery & Logistics
  { slug: "delivery-logistics", label: "Delivery & Logistics", icon: "toolbox" },
  { slug: "courier", label: "Courier", icon: "toolbox" },
  { slug: "packers-movers", label: "Packers & Movers", icon: "toolbox" },
  { slug: "loader", label: "Loader", icon: "toolbox" },
  { slug: "transport-service", label: "Transport Service", icon: "toolbox" },
  { slug: "truck-rental", label: "Truck Rental", icon: "toolbox" },
  { slug: "bike-delivery", label: "Bike Delivery", icon: "toolbox" },
  { slug: "tempo-rental", label: "Tempo Rental", icon: "toolbox" },

  // Domestic Help
  { slug: "domestic-help", label: "Domestic Help", icon: "toolbox" },
  { slug: "maid", label: "Maid", icon: "toolbox" },
  { slug: "cook", label: "Cook", icon: "toolbox" },
  { slug: "babysitter", label: "Babysitter", icon: "toolbox" },
  { slug: "nanny", label: "Nanny", icon: "toolbox" },
  { slug: "housekeeper", label: "Housekeeper", icon: "toolbox" },
  { slug: "gardener", label: "Gardener", icon: "toolbox" },
  { slug: "security-guard", label: "Security Guard", icon: "toolbox" },
  { slug: "pet-sitter", label: "Pet Sitter", icon: "toolbox" },
  { slug: "dog-walker", label: "Dog Walker", icon: "toolbox" },

  // Repair Services
  { slug: "repair-services", label: "Repair Services", icon: "toolbox" },
  { slug: "mobile-repair", label: "Mobile Repair", icon: "toolbox" },
  { slug: "watch-repair", label: "Watch Repair", icon: "toolbox" },
  { slug: "shoe-repair", label: "Shoe Repair", icon: "toolbox" },
  { slug: "bicycle-repair", label: "Bicycle Repair", icon: "toolbox" },
  { slug: "furniture-repair", label: "Furniture Repair", icon: "toolbox" },
  { slug: "clock-repair", label: "Clock Repair", icon: "toolbox" },
  { slug: "jewellery-repair", label: "Jewellery Repair", icon: "toolbox" },

  // Agriculture
  { slug: "agriculture", label: "Agriculture", icon: "toolbox" },
  { slug: "tractor-operator", label: "Tractor Operator", icon: "toolbox" },
  { slug: "farm-labour", label: "Farm Labour", icon: "toolbox" },
  { slug: "irrigation-technician", label: "Irrigation Technician", icon: "toolbox" },
  { slug: "dairy-worker", label: "Dairy Worker", icon: "toolbox" },
  { slug: "veterinary-assistant", label: "Veterinary Assistant", icon: "toolbox" },
  { slug: "horticulture-expert", label: "Horticulture Expert", icon: "toolbox" },

  // Freelancers
  { slug: "freelancers", label: "Freelancers", icon: "toolbox" },
  { slug: "virtual-assistant", label: "Virtual Assistant", icon: "toolbox" },
  { slug: "translator", label: "Translator", icon: "toolbox" },
  { slug: "transcriptionist", label: "Transcriptionist", icon: "toolbox" },
  { slug: "voice-over-artist", label: "Voice-over Artist", icon: "toolbox" },
  { slug: "resume-writer", label: "Resume Writer", icon: "toolbox" },
  { slug: "proofreader", label: "Proofreader", icon: "toolbox" },
  { slug: "data-entry-operator", label: "Data Entry Operator", icon: "toolbox" },
  { slug: "customer-support-executive", label: "Customer Support Executive", icon: "toolbox" },

  // Manufacturing & Industrial
  { slug: "manufacturing-industrial", label: "Manufacturing & Industrial", icon: "toolbox" },
  { slug: "cnc-operator", label: "CNC Operator", icon: "toolbox" },
  { slug: "machine-operator", label: "Machine Operator", icon: "toolbox" },
  { slug: "lathe-operator", label: "Lathe Operator", icon: "toolbox" },
  { slug: "electric-motor-rewinder", label: "Electric Motor Rewinder", icon: "toolbox" },
  { slug: "quality-inspector", label: "Quality Inspector", icon: "toolbox" },
  { slug: "factory-worker", label: "Factory Worker", icon: "toolbox" },

  // Miscellaneous
  { slug: "miscellaneous", label: "Miscellaneous", icon: "toolbox" },
  { slug: "astrologer", label: "Astrologer", icon: "toolbox" },
  { slug: "numerologist", label: "Numerologist", icon: "toolbox" },
  { slug: "vastu-consultant", label: "Vastu Consultant", icon: "toolbox" },
  { slug: "travel-agent", label: "Travel Agent", icon: "toolbox" },
  { slug: "tour-guide", label: "Tour Guide", icon: "toolbox" },
  { slug: "notary", label: "Notary", icon: "toolbox" },
  { slug: "tailor", label: "Tailor", icon: "toolbox" },
  { slug: "fashion-designer", label: "Fashion Designer", icon: "toolbox" },
  { slug: "embroidery-expert", label: "Embroidery Expert", icon: "toolbox" },
  { slug: "laundry-service", label: "Laundry Service", icon: "toolbox" },
  { slug: "dry-cleaning", label: "Dry Cleaning", icon: "toolbox" },
  { slug: "cobbler", label: "Cobbler", icon: "toolbox" },
  { slug: "scrap-collector", label: "Scrap Collector", icon: "toolbox" },
  { slug: "waste-management-service", label: "Waste Management Service", icon: "toolbox" },

  // Backward-compatible existing ones (optional, keep)
  { slug: "photography", label: "Photographers", icon: "camera" },
  { slug: "design", label: "Designers", icon: "palette" },
  { slug: "tutoring", label: "Tutors", icon: "book" },
  { slug: "music", label: "Musicians", icon: "music" },
  { slug: "events", label: "Event Planners", icon: "calendar" },
  { slug: "video", label: "Videographers", icon: "video" },
  { slug: "writing", label: "Writers", icon: "pen" },
  { slug: "fitness", label: "Fitness Trainers", icon: "dumbbell" },
  { slug: "other", label: "Other Freelancers", icon: "toolbox" },
] as const;

export const BENGALURU_AREAS = [
  // East Bengaluru
  "Whitefield",
  "Marathahalli",
  "Bellandur",
  "Sarjapur Road",
  "Brookefield",
  "KR Puram",
  "Mahadevapura",
  "Varthur",
  "Hoodi",
  "Kadubeesanahalli",

  // South Bengaluru
  "Electronic City (Phase 1 & 2)",
  "HSR Layout",
  "Koramangala",
  "BTM Layout",
  "JP Nagar",
  "Jayanagar",
  "Banashankari",
  "Bannerghatta Road",
  "Begur",
  "Arekere",

  // Central Bengaluru
  "Indiranagar",
  "MG Road",
  "Richmond Town",
  "Shanti Nagar",
  "Ulsoor",
  "Shivajinagar",
  "Frazer Town",
  "Cox Town",
  "Vasanth Nagar",

  // North Bengaluru
  "Hebbal",
  "Yelahanka",
  "Thanisandra",
  "Nagawara",
  "Hennur",
  "RT Nagar",
  "Sahakar Nagar",
  "Jakkur",
  "Vidyaranyapura",
  "New BEL Road",

  // West Bengaluru
  "Rajajinagar",
  "Malleshwaram",
  "Vijayanagar",
  "Basaveshwaranagar",
  "Nagarbhavi",
  "Kengeri",
  "RR Nagar",
  "Magadi Road",
  "Peenya",
  "Yeshwanthpur",

  // Devanahalli / Outer areas
  "Devanahalli",
  "Attibele",
  "Chandapura",
  "Anekal",
  "Dommasandra",
  "Gunjur",
  "Kothanur",
  "Horamavu",
  "Kalkere",
  "Seegehalli",
];


/** A talent's contact button is visible only while they're on trial or an active paid plan. */
export function canBeContacted(status: string, trialEndDate: string) {
  if (status === "active") return true;
  if (status === "trial") return new Date(trialEndDate) > new Date();
  return false;
}
